applications:
  t2clone:
    # The language and version for your app.
    type: 'nodejs:20'

    # The app's configuration when it's exposed to the web.
    web:
      commands:
        # No need for a start command since it's a static site.
        # start: npm start  # Commented out or removed
      locations:
        '/':
          # The public directory relative to the app root.
          root: '.'  # Assuming your static files are in the root directory
          # Forward resources to the app.
          passthru: true
          # What files to use when serving a directory.
          index: ["index.html"]
          # Allow files even without specified rules.
          allow: true

routes:
  "https://{default}/":
    type: upstream
    upstream: "t2clone:http"

  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
