applications:
  app:
    type: "nodejs:20"
    source:
      root: "/"
    web:
      locations:
        /:
          root: "public"
          index:
            - index.html
        /assets:
          root: "public/assets"
          allow: true
        /fonts:
          root: "public/fonts"
          allow: true
        /js:
          root: "public/js"
          allow: true

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"

  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
