applications:
  t2clone:
    type: 'nodejs:20'

  web:
    operations:
      start: "echo 'Static site deployment'"
    locations:
      '/':
        root: 'public'
        passthru: true
        index: ["index.html"]
        allow: true
      '/assets':
        root: 'public/assets'
        allow: true
      '/fonts':
        root: 'public/fonts'
        allow: true
      '/js':
        root: 'public/js'
        allow: true

routes:
  "https://{default}/":
    type: upstream
    upstream: "t2clone:http"

  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
