applications:
  t2clone:
    # Application source code directory
    source:
      root: "/"

    # Even though you're using static files, Upsun might still require a runtime type.
    # "nodejs:20" works fine for your static site, though it's not actively used for serving files.
    type: "nodejs:20"

    web:
      # Remove the start command since you're serving static files, not running a server.
      locations:
        "/":
          # Static files will be served from the root directory.
          root: "."
          # Set the default file to serve.
          index:
            - index.html

    # Remove unnecessary hooks, commands, and workers since you're not running a dynamic app.

# The routes of the project.
routes:
  "https://{default}/":
    type: upstream
    upstream: "t2clone:http"

  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
