applications:
  app:
    # The type of the application to build. Since your project is just HTML, CSS, and JS, you can keep this.
    type: "nodejs:20"
    source:
      root: "/"
    web:
      locations:
        /:
          # Set the root directory to where your static files are located
          root: "/"
          # Files to consider when serving a request for a directory.
          index:
            - index.html
